- hosts: appservers
  gather_facts: yes
  vars_prompt:
    - name: admin_password
      prompt: "What is the admin password?"
  tasks:

  - name: IIS & ASP.NET 4.5
    win_feature:
      name:
      - Web-Server
      - Web-Http-Redirect
      - Web-Log-Libraries
      - Web-Request-Monitor
      - Web-Http-Tracing
      - Web-Basic-Auth
      - Web-Windows-Auth
      - Web-App-Dev
      - Web-Net-Ext45
      - Web-AppInit
      - Web-Asp-Net45
      - Web-ISAPI-Ext
      - Web-ISAPI-Filter
      - Web-WebSockets
      - Web-Mgmt-Console
      - Web-Mgmt-Compat
      - Web-Metabase
      - Web-Mgmt-Service
      state: present
    register: iis_install

  - name: Reboot if installing Web-Server feature requires it
    win_reboot:
    when: iis_install.reboot_required